version: '3.7'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - spring-app1
      - spring-app2
    networks:
      - monitoring

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - monitoring

  spring-app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ass_system?serverTimezone=UTC&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=ass_system_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SERVER_NAME=app1
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    ports:
      - "8081:8080"
    networks:
      - monitoring
    depends_on:
      - mysql
      - redis

  spring-app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ass_system?serverTimezone=UTC&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=ass_system_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SERVER_NAME=app2
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    ports:
      - "8082:8080"
    networks:
      - monitoring
    depends_on:
      - mysql
      - redis

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
      - spring-app1
      - spring-app2
    networks:
      - monitoring

  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ass_system
      MYSQL_USER: ass_system_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - monitoring

volumes:
  grafana-storage:
  mysql_data:

networks:
  monitoring:
    driver: bridge
