server {
    listen 80;
    server_name localhost;
}

server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;

    location /api/redis {
        proxy_pass http://was3:8083;
    }

    location /api {
        proxy_pass http://was_backend;
    }

    upstream was_backend {
        server was1:8081;
        server was2:8082;
    }
}
